# Project: Laboratorio 08
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = estadistica.o main.o
LINKOBJ  = estadistica.o main.o
LIBS     = -L"C:/Users/Josue/Dev-Cpp/MinGW64/lib" -L"C:/Users/Josue/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Josue/Dev-Cpp/MinGW64/include" -I"C:/Users/Josue/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Josue/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Josue/Dev-Cpp/MinGW64/include" -I"C:/Users/Josue/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Josue/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Josue/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Laboratorio 08.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

estadistica.o: estadistica.cpp
	$(CPP) -c estadistica.cpp -o estadistica.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
